version: '3.8'

services:
  ariala-web:
    build:
      context: .
      args:
        - VITE_API_KEY=${API_KEY}
    container_name: ariala_taberna_web
    ports:
      - "8080:8080"
    restart: always
    networks:
      - ariala-network

networks:
  ariala-network:
    driver: bridge