version: '3.8'

services:
  ariala-web:
    build: .
    container_name: ariala_taberna_web
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
    restart: always
    networks:
      - ariala-network

networks:
  ariala-network:
    driver: bridge